name: DeathSwap
version: 1.0
main: de.mlehrke.deathswap.DeathSwapPlugin
api-version: 1.21
commands:
  start:
    description: Startet das Player Swapping
  invsee:
    description: Lässt spieler in das Inventar von anderen schauen. Admins können inventare bearbeiten.
  swapnow:
    description: Lässt einen Admin den Swap sofort auslösen
  reset:
    description: Lässt einen Admin die Game Welt resetten.